#OPERATORS ARE USED TO GIVE SOLUTIONS TO OPERANDS IN AN EXPRESSIONS
#TYPES OF OPERATORS INCLUDES: LOGICAL,ARITHMETIC,RELATIONAL,MEMBERSHIP,IDENTITY,BITWISE,ASSIGNMENT OPERATORS
#ARITHMETIC INCLUDES=+,-,%,*,/,// ETC
#LOGICAL INCLUDES:AND,OR,NOT
#RELATIONAL INCLUDES:<,>,<=,>=
#MEMBERSHIP INCLUDES:IN,NOT IN
#IDENTITY INCLUDES:IS,IS NOT
#BITWISE INCLUDES:| AND CONVERTING TO BINARY
#ASSIGNMENT OPERATOR: +=,-=,%=,*= ETC
