#VARIABLES ARE MEMORY LOCATIONS
#WHEN A VARIABLE IS CREATED,A NEW SPACE IS CREATED IN THE MEMORY
#A VARIABLE CAN BE ASSIGNED USING A "=" SIGN
#THE OBJECT TO THE LEFT OF THE = SIGN IS CALLED A VARIABLE
#THE OBJECT TO THE RIGHT IS THE ASSIGNED ITEM
# WE CAN HAVE MULTIPLE ASSIGNMENTS LIKE THE FOLLOWING:
#A=B=C=1,A,B,C,ARE ASSIGNED TO THE MEMORY LOCATIONS
#A,B,C=1,2,3 IS ALSO A TYPE OF MULTIPLE ASSIGNMENTS
#STANDARD DATA TYPES INCLUDES:STRINGS,NUMBERS I.E INT,FLOAT,COMPLEX NUMBERS,LISTS,TUPLES AND DICTIONARIES
#DATA TYPE CONVERSIONS:INT(X),FLOAT(X),DICT(X)
