#CHAPTER 4
#IDENTIFIERS ARE NAMES THAT ARE USED TO IDENTIFY VARIABLES,OBJECTS,STRINGS AND OTHERS
#EXAMPLES OF AN IDENTIFIER INCLUDES:
#NAMES="SOLAPE",NAMES IS AN IDENTIFIER AND ALSO A VARIABLE(MEMORY LOCATION)
#AN IDENTIFIER CAN START FROM THE LETTERS A-Z OR a-z
#PYTHON IS CASE SENSITIVE
#RULES FOR NAMING IN PYTHON INCLUDES THE FOLLOWING
#A CLASS NAME MUST BEGIN WITH AN UPPER CASE,THEN THE REMAINING IDENTIFIERS
#CAN START WITH LOWER CASES
#AN IDENTIFIER WITH AN UNDERSCORE IS CALLED A "PRIVATE IDENTIFIER"
#AN IDENTIFIER WITH TWO LEADING UNDERSCORES IS CALLED A "STRONG PRIVATE IDENTIFIER"
#AN IDENTIFIER WITH TWO ENDING UNDERSCORES IS CALLED "A LANGUAGE DEFINED SPECIAL NAME"
#---------------------------
#PYTHON RESERVED WORDS: THE RESERVED WORDS ARE ALL IN LOWER CASES
#EXAMPLES OF THE RESERVED WORDS ARE:and,not,or,if,import,pass,break,elif,else etc.
#----------------------------
#MULTILINE STATEMENTS:\,''',[],ETC
#SUITES ARE LINES OF CODES UNDER A BLOCK EXPRESSION
